# https://docs.travis-ci.com/user/deployment/pages
# http://derekweitzel.com/2017/02/08/deploying-docs-on-github-with-travisci
# https://stackoverflow.com/questions/50892018/auto-build-an-mkdocs-documentation-in-travis-ci
# https://github.com/mkdocs/mkdocs/issues/632

language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - mkdocs build --verbose #--strict
deploy:
  provider: script
  # no multi-line allowed
  script: .travis/deploy_gh_pages.sh
  on:
    branch: master
